import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",

  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  theme: {
    extend: {
      colors: {
        primary: "#dbfcff",
        tertiary: "#f8f4ff",
        "surface-variant": "#2d3449",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#07006c",
        "surface-container-highest": "#2d3449",
        "inverse-primary": "#006970",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "outline-variant": "#3b494b",
        "inverse-surface": "#dae2fd",
        "on-error": "#690005",
        background: "#0b1326",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "secondary-container": "#00a572",
        "on-secondary-fixed": "#002113",
        "inverse-on-surface": "#283044",
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#222a3d",
        "on-primary-fixed": "#002022",
        "error-container": "#93000a",
        "surface-container-lowest": "#060e20",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#00dbe9",
        "surface-tint": "#00dbe9",
        "surface-container-low": "#131b2e",
        outline: "#849495",
        "primary-fixed": "#7df4ff",
        "on-primary-container": "#006970",
        "secondary-fixed-dim": "#4edea3",
        "on-surface-variant": "#b9cacb",
        "surface-container": "#171f33",
        "on-tertiary-container": "#494bd7",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#003824",
        "on-tertiary": "#1000a9",
        "primary-container": "#00f0ff",
        surface: "#0b1326",
        "on-primary-fixed-variant": "#004f54",
        "tertiary-container": "#d7d6ff",
        error: "#ffb4ab",
        secondary: "#4edea3",
        "on-background": "#dae2fd",
        "on-secondary-container": "#00311f",
        "on-primary": "#00363a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "1rem",
        xs: "0.5rem",
        md: "1.5rem",
        base: "4px",
        gutter: "24px",
        lg: "2.5rem",
        xl: "4rem",
        "container-max": "1200px",
      },
      fontFamily: {
        h1: ["Inter"],
        "label-caps": ["Space Grotesk"],
        body: ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "code-md": ["JetBrains Mono"],
        h3: ["Inter"],
        h2: ["Inter"],
      },
      fontSize: {
        h1: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-md": ["15px", { lineHeight: "1.5", fontWeight: "500" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h2: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },

  plugins: [],
};

export default config;
